GET https://localhost/processi


###

GET https://localhost/nuovoprocesso

###


DELETE https://localhost/deleteall

###

POST  https://localhost/nuovoprocesso
Content-Type: application/json

{
    "titolo": "Gestione scorte in cloud"
}
###

PATCH  https://localhost/modificaprocesso
Content-Type: application/json

{
   "id": "3b706600-6430-4dfd-9ed4-32ebdf8ff720",
   "titolo": "Gestione scorte in cloud",
   "autori": ["Alberto Bregliano"],
   "approvatori": ["Valeria Allegretti", "Valeria Pipornetti"],
   "verificatori": ["Guido Bruno"],
   "flussoimmagine": "/static/flusso.png"
}