GET https://localhost/processi


###

GET https://localhost/nuovoprocesso

###

GET https://localhost/attivita

###

GET https://localhost/attivita/4a90f362-b97e-4e6c-a587-43478e9f36c5

###


GET https://localhost/processo/7371a348-af61-48ed-931a-47bb6744f960

###


DELETE https://localhost/deleteall

###

POST  https://localhost/processi/new/
Content-Type: application/json

{
    "titolo": "Gestione scorte in cloud"
}
###

PATCH  https://localhost/modificaprocesso
Content-Type: application/json

{
   "id": "eb9ead41-8e37-40fa-ad0b-1f2afa837ea9",
   "autori": ["Alberto Bregliano"]
}